services:
  stremthru:
    image: muniftanjim/stremthru:latest
    container_name: stremthru
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - .env
    depends_on:
      stremthru_redis:
        condition: service_healthy
      stremthru_postgres:
        condition: service_healthy
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stremthru.rule=Host(`${STREMTHRU_HOSTNAME?}`)"
      - "traefik.http.routers.stremthru.entrypoints=websecure"
      - "traefik.http.routers.stremthru.tls.certresolver=letsencrypt"
      - "traefik.http.routers.stremthru.middlewares=authelia@docker"
      - "traefik.http.services.stremthru.loadbalancer.server.port=8080"
    profiles:
      - stremthru
      - all

  stremthru_redis:
    image: redis:latest
    container_name: stremthru_redis
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - stremthru
      - all

  stremthru_postgres:
    image: postgres:17-alpine
    container_name: stremthru_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stremthru"]
      start_period: 1m
    environment:
      POSTGRES_DB: stremthru
      POSTGRES_USER: stremthru
      POSTGRES_PASSWORD: stremthru
    volumes:
      - ${DOCKER_DATA_DIR}/stremthru/db:/var/lib/postgresql/data
