services:
  aiometadata:
    image: ghcr.io/cedya77/aiometadata:latest
    container_name: aiometadata
    restart: unless-stopped
    expose:
      - ${PORT:-1337}
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aiometadata.rule=Host(`${AIOMETADATA_HOSTNAME?}`)"
      - "traefik.http.routers.aiometadata.entrypoints=websecure"
      - "traefik.http.routers.aiometadata.tls.certresolver=letsencrypt"
      - "traefik.http.routers.aiometadata.middlewares=authelia@docker"
      - "traefik.http.services.aiometadata.loadbalancer.server.port=${PORT:-1337}"
    volumes:
      - ${DOCKER_DATA_DIR}/aiometadata/data:/app/addon/data
    depends_on:
      aiometadata_redis:
        condition: service_healthy

  aiometadata_redis:
    image: redis:latest
    container_name: aiometadata_redis
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    volumes:
      - ${DOCKER_DATA_DIR}/aiometadata/cache:/data
    command: redis-server --appendonly yes --save 60 1
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
